mkdir -p /home/ubuntu/conf
mkdir -p /home/ubuntu/logs
mkdir -p /home/ubuntu/software
mkdir -p /home/ubuntu/storage
mkdir -p /home/ubuntu/workload
mkdir -p /home/ubuntu/logs/apps 
mkdir -p /home/ubuntu/logs/hadoop 
mkdir -p /home/ubuntu/storage/data/local/nm
mkdir -p /home/ubuntu/storage/data/local/tmp
mkdir -p /home/ubuntu/storage/hdfs/hdfs_dn_dirs 
mkdir -p /home/ubuntu/storage/hdfs/hdfs_nn_dir 
mkdir -p /home/ubuntu/workload 
mkdir -p /home/ubuntu/storage/da/spark/rdds_shuffle 
mkdir -p /home/ubuntu/logs/spark 
mkdir -p /home/ubuntu/storage/data/spark/worker 