#!/usr/bin/python
import numpy as np
import scipy.sparse
import pickle
import xgboost as xgb

import matplotlib.pyplot as plt
### simple example
# load file from text file, also binary buffer generated by xgboost
dtrain = xgb.DMatrix('agaricus.txt.train')
dtest = xgb.DMatrix('agaricus.txt.test')

# specify parameters via map, definition are same as c++ version
param = {'max_depth':2, 'eta':1, 'silent':1, 'objective':'binary:logistic'}

# specify validations set to watch performance
watchlist = [(dtest, 'eval'), (dtrain, 'train')]
num_round = 20
bst = xgb.train(param, dtrain, num_round, watchlist)
x = range(1,21)
plt.plot(x,dtest)
plt.plot(x, dtrain)
plt.show()